# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 17:20


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20170906_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wagtailimages.Image'),
        ),
    ]
