# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 17:47


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('cms', '0012_auto_20170906_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='wagtailimages.Image'),
            preserve_default=False,
        ),
    ]
