# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-22 12:49


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('cms', '0018_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsindexpage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wagtailimages.Image'),
        ),
    ]
