# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-22 12:50


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_newsindexpage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsindexpage',
            name='image',
        ),
    ]
