# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-17 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_auto_20210813_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibitionfeaturepage',
            options={'ordering': ['feature_number']},
        ),
        migrations.AddField(
            model_name='exhibitionfeaturepage',
            name='feature_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ForeignKey(blank=True, help_text='(To specify the HTML alt attribute, click Edit and change the title field.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(blank=True, default='', help_text='The full title of the artwork.', max_length=255),
        ),
    ]
